config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create] do
    resources :reviews, only: [:index, :new, :create, :show]
  end
  resources :restaurants, only: [:show]

  namespace :admin do
    resources :restaurants, :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def show

  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
    redirect_to restaurant_path(@review.restaurant)
  end

  def show

  end

  def destroy
    @review.destroy
    redirect_to review_path
  end

  def edit
  end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end


  private

  def set_review
    @review = review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit your Restaurant</h1>

<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.submit %>
<% end %>


<%= link_to "Delete", restaurant_path(@restaurant),
  method: :delete,
  data: {confirm: "Are you sure you want to delete this restaurant? You won't be able to get it back!"} %>

  <%= link_to "Back to overview", restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Overview of restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <h2><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></h2>
  <p><%= restaurant.address %></p>
  <%= link_to "Delete", restaurant_path(restaurant),
  method: :delete,
  data: {confirm: "Are you sure you want to delete this restaurant? You won't be able to get it back!"} %>
  <%= link_to "Edit", edit_admin_restaurant_path(restaurant) %>
<% end %>

<%= link_to "Create a new Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>
  <%= form_for(@restaurant) do |f| %>
    <% if @restaurant.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to overview", restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Details of restaurant</h1>

<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>


<h2>This are the reviews of this restaurant:</h2>
<% @restaurant.reviews.each do |review| %>
  <h2><%=  review.rating %></h2>
  <p><%= review.content %></p>
<% end %>

<%= link_to "Delete restaurant", restaurant_path(@restaurant),
  method: :delete,
  data: {confirm: "Are you sure you want to delete this restaurant? You won't be able to get it back!"} %>
  <%= link_to "Edit", edit_admin_restaurant_path(@restaurant) %>


<%= link_to "Back to overview", restaurants_path %>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Create a new review about <%= @restaurant.name %></h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Back to restaurant", restaurant_path(@restaurant) %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>